name: Run Insomnia Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - uat
          - prod

  push:
    branches:
      - main

  pull_request:

jobs:
  insomnia-tests:
    runs-on: ubuntu-latest

    env:
      ENV_NAME: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - name: Install Inso CLI
        run: npm install -g insomnia-inso

      - name: Check insomnia version
        run: inso --version

      - name: Show Selected Environment
        run: echo "Running tests on $ENV_NAME environment"

      - name: Run Bookstore Collection
        run: |
          inso run test Insomnia_2026-05-23 \
          --workingDir "./insomnia"


